### DISCUSSION TITLE
error running any Ansible task

### DISCUSSION THREAD

**Discussion by jkrilov** [lowlydba/lowlydba.sqlserver#137] [Q&A] [answered]
I get the following error when I try to use any lowlydba Ansible module.  In this case instance_info

```
ParserError:  /root/.ansible/tmp/ansible-tmp-1669653577.4521654-1601096-258718634814176/AnsiballZ_instance_info.ps1:159 
    Line | 
     159 |   {\"module_entry\": \"… 
         |   ~ 
         |   unexpected token ' ', expected 'begin', 'process', 'end', 'clean', or 
         |   'dynamicparam'. \n",
        "module_stdout": "",
        "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
        "rc": 1
    }
```

This is what my task looks like.  I've confirmed the values of the variables I'm passing as they work with other non-lowlydba tasks. 
```
- name: Get Instance Info
  lowlydba.sqlserver.instance_info:
    sql_instance: "{{ SQL_HOSTNAME }}"
    sql_username: "{{ SQL_ADMIN_USER }}"
    sql_password: "{{ SQL_ADMIN_PASS }}"
  register: sql_info
  ignore_errors: true
```

I'm running Ansible on a Ubuntu server with the lowlydba.sqlserver collection, latest powershell, and dbatools installed. 

Any help would be appreciated!
