### DISCUSSION TITLE
Error handling / Output (see warnings for details. )

### DISCUSSION THREAD

**Discussion by tovoro** [lowlydba/lowlydba.sqlserver#263] [Q&A] [answered]
How do you people handle errors within the module? 

I would like the people who run the ansible job to see what the exact error is, but cant seem to find out where the message is returned exactly: 

For example: 
When I try to restore a DB that already exists (with_replace set to false), the module outputs: 
"Error restoring database: Database Testdb unable to be restored, see warnings for details."

How can I access the "warnings" within the ansible playbook? 

Thanks for your help

**Comment by lowlydba** [comment]
That particular error message is defined upstream by the dbatools pwsh module. They have made the choice to put the details as a warning log, and just have the error message tell you to refer back to them.

I'm not positive if this will work, but have you tried registering the output and then printing stderr? Something like:

```yml
 - name: Create a database
      lowlydba.sqlserver.database:
        database: "x"
      register: result
- name: Display stderr
      debug:
        msg: "{{ result.stderr }}"
```

If that doesn't work, then I think it'd mean it would take an enhancement to explicitly capture and display warning messages overall. 

@briantist Any thoughts?
