### ISSUE TITLE
[Bug] Login always reports changed

### ISSUE THREAD

**Issue by Joey40** [lowlydba/lowlydba.sqlserver#164]
**Describe the bug**
lowlydba.sqlserver.login always shows as changed

**To Reproduce**

Redacted code snipped:

```
- name: Create login
  lowlydba.sqlserver.login:
    sql_instance: "{{ SQL_HOSTNAME }}"
    sql_username: "{{ SQL_ADMIN_USER }}"
    sql_password: "{{ SQL_ADMIN_PASS }}"
    login: "{{ SQL_USER }}"
    password: "{{ SQL_PASS }}"
    password_expiration_enabled: false
    password_policy_enforced: false
    language: "us_english"
```

**Expected behavior**
Login should only change when first created. 

**Versions(please complete the following information):**

* OS: Windows 2019
* SQL Server: Azure SQL MI
* PowerShell: 7.3.1

**Additional context**
