### ISSUE TITLE
[Bug] Documentation for lowlydba.sqlserver.sa module has incorrect parameter

### ISSUE THREAD

**Issue by OsirisDBA** [lowlydba/lowlydba.sqlserver#188]
The current version (lowlydba.sqlserver 1.3.1) of the documentation available for the [sa module](https://lowlydba.github.io/lowlydba.sqlserver/branch/main/collections/lowlydba/sqlserver/sa_module.html) contains an error in the examples section

```
- name: Disable sa login
  lowlydba.sqlserver.sa:
    sql_instance: sql-01.myco.io
    disable: true
```

Should become
```
- name: Disable sa login
  lowlydba.sqlserver.sa:
    sql_instance: sql-01.myco.io
    enable: false
```
