### ISSUE TITLE
[Request] Provide a way to avoid resetting login passwords if login exists.

### ISSUE THREAD

**Issue by OsirisDBA** [lowlydba/lowlydba.sqlserver#192]
As part of my company's infrastructure-as-code initiative I'm trying to generate a host_vars file that contains all items on the instance. One of the problems I've noticed relates to user logins. I'm utilizing a list of dictionaries structure to describe the logins

``` yaml
sqlserver_cluster_logins:
  - login: SomeServiceAccount
    password: <lookup>
    password_must_change: false
    password_policy_enforced: true
    password_expiration_enabled: false
    enabled: true

  - login: SomeUserAccount
    password: <generated generic default>
    password_must_change: true
    password_policy_enforced: true
    password_expiration_enabled: true
    enabled: true
```
For these user accounts I don't want to reset the password if the account already exists. Yet I won't know if this is a new account or and existing account until inside the login module. 

One solution I've considered is adding a new parameter to the login module such as skip_password_reset: (true|false) that would ignore the password parameter if the login already exists.

Otherwise, I'll need to fallback to using win_powershell and calling Get-DbaLogin/Set-DbaLogin/Remove-DbaLogin myself. 

It's simple to implement but I'd like to hear your thoughts on the issue.
